/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Regions',
      [
        {
          name: 'Белгородская область',
          federalDist_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Брянская область',
          federalDist_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Владимирская область',
          federalDist_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Воронежская область',
          federalDist_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ивановская область',
          federalDist_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Калужская область',
          federalDist_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Костромская область',
          federalDist_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Курская область',
          federalDist_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Липецкая область',
          federalDist_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Московская область',
          federalDist_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Орловская область',
          federalDist_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Рязанская область',
          federalDist_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Смоленская область',
          federalDist_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Тамбовская область',
          federalDist_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Тверская область',
          federalDist_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Тульская область',
          federalDist_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ярославская область',
          federalDist_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'г. Москва',
          federalDist_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Республика Карелия',
          federalDist_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Республика Коми',
          federalDist_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Архангельская область',
          federalDist_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Вологодская область',
          federalDist_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Калининградская область',
          federalDist_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ленинградская область',
          federalDist_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Мурманская область',
          federalDist_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Новгородская область',
          federalDist_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Псковская область',
          federalDist_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'г. Санкт-Петербург',
          federalDist_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ненецкий авт. округ',
          federalDist_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Республика Башкортостан',
          federalDist_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Республика Марий Эл',
          federalDist_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Республика Мордовия',
          federalDist_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Республика Татарстан',
          federalDist_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Удмуртская Республика',
          federalDist_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Чувашская Республика',
          federalDist_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Кировская область',
          federalDist_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Нижегородская область',
          federalDist_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Оренбургская область',
          federalDist_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Пензенская область',
          federalDist_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Пермская область',
          federalDist_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Самарская область',
          federalDist_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Саратовская область',
          federalDist_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ульяновская область',
          federalDist_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Коми-Пермяцкий авт. округ',
          federalDist_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Курганская область',
          federalDist_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Свердловская область',
          federalDist_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Тюменская область',
          federalDist_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Челябинская область',
          federalDist_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ханты-Мансийский авт. округ',
          federalDist_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ямало-Ненецкий авт. округ',
          federalDist_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Республика Дагестан',
          federalDist_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Республика Ингушетия',
          federalDist_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Кабардино-Балкарская Республика',
          federalDist_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Карачаево-Черкесская Республика',
          federalDist_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Республика Северная Осетия - Алания',
          federalDist_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Чеченская Республика',
          federalDist_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ставропольский край',
          federalDist_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Республика Адыгея',
          federalDist_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Республика Калмыкия',
          federalDist_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Республика Крым',
          federalDist_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Краснодарский край',
          federalDist_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Астраханская область',
          federalDist_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Волгоградская область',
          federalDist_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ростовская область',
          federalDist_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'г. Севастополь',
          federalDist_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Республика Алтай',
          federalDist_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Республика Тыва',
          federalDist_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Республика Хакасия',
          federalDist_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Алтайский край',
          federalDist_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Красноярский край',
          federalDist_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Иркутская область',
          federalDist_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Кемеровская область',
          federalDist_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Новосибирская область',
          federalDist_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Омская область',
          federalDist_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Томская область',
          federalDist_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Республика Бурятия',
          federalDist_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Республика Саха (Якутия)',
          federalDist_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Забайкальский край',
          federalDist_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Камчатский край',
          federalDist_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Приморский край',
          federalDist_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Хабаровский край',
          federalDist_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Амурская область',
          federalDist_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Магаданская область',
          federalDist_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Сахалинская область',
          federalDist_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Еврейская авт. область',
          federalDist_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Чукотский авт. округ',
          federalDist_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {},
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Regions', null, {});
  },
};
